[package]
name = "resozi"
version = "0.1.0"
edition = "2021"

[dependencies]
# gtk = { version = "0.9.1", package = "gtk4" }
gtk4 = "0.9.1"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
# wry = "0.43.1"
